#!/bin/bash

export CACA_DRIVER=ncurses
echo "YTerm 1.0 by Kocotian"
exec 2> /dev/null

# watch by id

if [ $1 == '-w' ]
then
	echo "Playing from: https://alphayt.pl/yterm/watch?v=$2&q=h"
	mplayer -really-quiet -framedrop "https://alphayt.pl/yterm/watch?v=$2&q=h"
elif [ $1 == '-wq' ]
then
	if [ $2 == 'l' ]
	then
		echo "Playing from: https://alphayt.pl/yterm/watch?v=$3&q=l"
		mplayer -really-quiet -framedrop "https://alphayt.pl/yterm/watch?v=$3&q=l"
	elif [ $2 == 'h' ]
	then
		echo "Playing from: https://alphayt.pl/yterm/watch?v=$3&q=h"
		mplayer -really-quiet -framedrop "https://alphayt.pl/yterm/watch?v=$3&q=h"
	fi
elif [ $1 == '-wt' ]
then
	echo "Playing from: https://alphayt.pl/yterm/watch?v=$2&q=l"
	mplayer -really-quiet -hardframedrop -vo caca "https://alphayt.pl/yterm/watch?v=$2&q=l"
elif [ $1 == '-wqt' ]
then
	if [ $2 == 'l' ]
	then
		echo "Playing from: https://alphayt.pl/yterm/watch?v=$3&q=l"
		mplayer -really-quiet -hardframedrop -vo caca "https://alphayt.pl/yterm/watch?v=$3&q=l"
	elif [ $2 == 'h' ]
	then
		echo "Playing from: https://alphayt.pl/yterm/watch?v=$3&q=h"
		mplayer -really-quiet -hardframedrop -vo caca "https://alphayt.pl/yterm/watch?v=$3&q=h"
	fi

# search

elif [ $1 == '-s' ]
then
	echo "Playing from: https://alphayt.pl/yterm/search?s=${2//\ /%20}&q=h"
	mplayer -really-quiet -framedrop "https://alphayt.pl/yterm/search?s=${2//\ /%20}&q=h"
elif [ $1 == '-sq' ]
then
	if [ $2 == 'l' ]
	then
		echo "Playing from: https://alphayt.pl/yterm/search?s=${3//\ /%20}&q=l"
		mplayer -really-quiet -framedrop "https://alphayt.pl/yterm/search?s=${3//\ /%20}&q=l"
	elif [ $2 == 'h' ]
	then
		echo "Playing from: https://alphayt.pl/yterm/search?s=${3//\ /%20}&q=h"
		mplayer -really-quiet -framedrop "https://alphayt.pl/yterm/search?s=${3//\ /%20}&q=h"
	fi
elif [ $1 == '-st' ]
then
	echo "Playing from: https://alphayt.pl/yterm/search?s=${2//\ /%20}&q=l"
	mplayer -really-quiet -hardframedrop -vo caca "https://alphayt.pl/yterm/search?s=${2//\ /%20}&q=l"
elif [ $1 == '-sqt' ]
then
	if [ $2 == 'l' ]
	then
		echo "Playing from: https://alphayt.pl/yterm/search?s=${3//\ /%20}&q=l"
		mplayer -really-quiet -hardframedrop -vo caca "https://alphayt.pl/yterm/search?s=${3//\ /%20}&q=l"
	elif [ $2 == 'h' ]
	then
		echo "Playing from: https://alphayt.pl/yterm/search?s=${3//\ /%20}&q=h"
		mplayer -really-quiet -hardframedrop -vo caca "https://alphayt.pl/yterm/search?s=${3//\ /%20}&q=h"
	fi
else
	echo "Usage:
	-w <id>                 Watch by id
	-wq <quality> <id>      Watch by id with selected quality (h for high or l for low)
	
	-s <phrase>             Watch the video searched by phrase
	-sq <quality> <phrase>  Watch the video searched by phrase with selected quality

	Add 't' to the option to watch video in terminal, for example:
	-st <phrase>            Watch the video by phrase in terminal
	-wqt <quality> <phrase> Watch by id with selected quality in terminal"

fi
